// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHAdrLAByN6r_a6vuwN9dU4LV03QY35CA',
    appId: '1:630030234282:web:8f6d9e757efac122b256d3',
    messagingSenderId: '630030234282',
    projectId: 'medico-43fb0',
    authDomain: 'medico-43fb0.firebaseapp.com',
    storageBucket: 'medico-43fb0.firebasestorage.app',
    measurementId: 'G-9RDT0ZNCCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOaw8Gw1dwMRs2kWPAucCpNNevmWdDWo8',
    appId: '1:630030234282:android:7dbeaf3e5a95ef5bb256d3',
    messagingSenderId: '630030234282',
    projectId: 'medico-43fb0',
    storageBucket: 'medico-43fb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV_-5zt4sgIvxi5mZhwdwX1SkgnaTLry4',
    appId: '1:630030234282:ios:a36d136de856660fb256d3',
    messagingSenderId: '630030234282',
    projectId: 'medico-43fb0',
    storageBucket: 'medico-43fb0.firebasestorage.app',
    iosBundleId: 'com.example.assigmedico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV_-5zt4sgIvxi5mZhwdwX1SkgnaTLry4',
    appId: '1:630030234282:ios:a36d136de856660fb256d3',
    messagingSenderId: '630030234282',
    projectId: 'medico-43fb0',
    storageBucket: 'medico-43fb0.firebasestorage.app',
    iosBundleId: 'com.example.assigmedico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHAdrLAByN6r_a6vuwN9dU4LV03QY35CA',
    appId: '1:630030234282:web:b811d816b36e4391b256d3',
    messagingSenderId: '630030234282',
    projectId: 'medico-43fb0',
    authDomain: 'medico-43fb0.firebaseapp.com',
    storageBucket: 'medico-43fb0.firebasestorage.app',
    measurementId: 'G-G8VWXPLPHR',
  );
}
